version: "3.9"

services:
  # ─── Elasticsearch ───
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.12  # ⇦ 和你 requirements 里 elasticsearch-py 版本对应
    container_name: rag-es
    environment:
      - discovery.type=single-node         # 单节点，省掉选主节点流程
      - cluster.name=rag-local
      - node.name=rag-es-01
      - xpack.security.enabled=false       # 纯开发环境：禁用安全特性
      - ES_JAVA_OPTS=-Xms1g -Xmx1g         # JVM 内存
    ports:
      - "9200:9200"                        # 本机 9200 ←→ 容器 9200
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - rag-net



volumes:
  esdata:

networks:
  rag-net:
